## Numpy: Numerical Python, manipular arrays

* Arrays Unidimensionales, bidimensionales y multidimesnionales

In [2]:
import numpy as np

#Array Unidimensional
array = np.array([range(1, 5)])

array, type(array)

(array([[1, 2, 3, 4]]), numpy.ndarray)

In [6]:
notes = np.arange(1, 6, 0.5)

array2 = np.array(notes, dtype=float)

array2, type(array2), type(array2[0])


(array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5]),
 numpy.ndarray,
 numpy.float64)

In [11]:
notes = [1,2,3]

notes_array = np.array(notes, dtype=int)

notes_array, type(notes_array[0]) , type(notes_array), notes_array.ndim, notes_array.shape



(array([1, 2, 3]), numpy.int64, numpy.ndarray, 1, (3,))

In [3]:
#Array con numeros aleatorios
test = np.random.choice([5, 4, 2], size=3, replace=True)  #el attr replace indica si se repiten o no los valores
test2 = np.random.choice([5, 4, 2], size=3, replace=False)
test, test2

(array([5, 2, 5]), array([4, 5, 2]))

In [20]:
# Un arreglo unidimensinal es un vector(axis=0), un arreglo bidimensional es una matriz(axis = 0, axis = 1)
#Array tridimensional es un cubo (axis=0,1,2)
#Dimensiones = ejes(axes)

notes1 = range(1, 6)
notes2 = range(6, 11)
notes3 = range(11, 16)
notes4 = range(16, 21)

#print(len(notes1), len(notes2))
#print(notes1, notes2)

array2D = np.array((notes1, notes2, notes3, notes4), dtype=float) #Matriz 4*5

print(array2D)

#Ndim: Dimension de un array
print(f"\n La dimensión del array es de: {array2D.ndim}")

#Shape: Tamaño de un array
print(f"\n El tamaño del array es de: {array2D.shape}")

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]

 La dimensión del array es de: 2

 El tamaño del array es de: (4, 5)


In [19]:
# i = row, j = column or element in row

a = [[1, 2, 3, 4], [5, 6], [7, 8, 9]]
'''for i in range(len(a)):
    #i = 0, 1, 2
    for j in range(len(a[i])):
        #j = 0, 1, 2, 3; 0, 1; 0, 1, 2

        #e = elementos contenidos en los elementos(listas) del array "a"
        e = (a[i])[j]
        print(e)'''

for row in a:
    for e in row:
        print(e, end=" ")

1 2 3 4 5 6 7 8 9 

In [7]:
# Array de n dimensiones/Multidimensionales, más de dos dimensiones
# Array multidimensional: son varias matrices(axis=0,1,2...,n)

b = [[1, 2, 3, 4], [5, 6 ,7, 8], [9, 10, 11, 12]]
c= [[1, 2, 3, 4], [5, 6 ,7, 8], [9, 10, 11, 12]]

multi_array = np.array((b, c), dtype=int)
print(f"Multidimensional array = \n{multi_array}\n\n Dimension = {multi_array.ndim}\n Shape = {multi_array.shape}")

Multidimensional array = 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]

 Dimension = 3
 Shape = (2, 3, 4)


In [28]:
b = [[1, 2, 3, 4], [5, 6 ,7, 8], [9, 10, 11, 12]]
c= [[1, 2, 3, 4], [5, 6 ,7, 8], [9, 10, 11, 12]]
d = [[1, 2, 3, 4], [5, 6 ,7, 8], [9, 10, 11, 12]]
nArray = np.array((b, c, d), dtype=int)
print(f"Multidimensional array = \n{nArray}\n\n Dimension = {nArray.ndim}\n Shape = {nArray.shape}")

Multidimensional array = 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]

 Dimension = 3
 Shape = (3, 3, 4)


### Arrays especiales

* zeros: todos los elementos son = 0
* ones: todos los elementos son = 1
* identity: matriz identidad
* arange: array con rango específico

In [8]:
zeros = np.zeros((3, 4), dtype=int)
print(zeros, "\n")

ones = np.ones((2, 2), dtype=float)
print(ones, "\n")

identity = np.identity((3), dtype=int)
print(identity, "\n")

arange = np.arange(1, 6)
print(arange)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

[[1. 1.]
 [1. 1.]] 

[[1 0 0]
 [0 1 0]
 [0 0 1]] 

[1 2 3 4 5]


### Operaciones Básicas

In [9]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
lista = list(range(1, 11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
arr.shape = (2, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
arr.shape = (5, 2)
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [22]:
#Adición

narray = arr + arr #Con arrays se hacen operaciones aritméticas
narray.shape = (2, 5)

print(narray, "\n")

print(lista + lista) #Las listas se concatenan

[[ 2  4  6  8 10]
 [12 14 16 18 20]] 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
#Resta
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Multiplicación

print(arr * arr)

[  1   4   9  16  25  36  49  64  81 100]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[          1           4          27         256        3125       46656
      823543    16777216   387420489 10000000000]


In [ ]:
#División

print(arr / arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#Exponenciación
print(arr ** arr)

[          1           4          27         256        3125       46656
      823543    16777216   387420489 10000000000]
