In [43]:
#PRODUCTO DE ARRAYS
# Se pude usar: np.dot(a, b), A @ B or np.matmul(a, b)

import numpy as np

a = np.array([1, 2, 3], float)
b = np.array([0, 5, 1/2], float)

print("A =", a)
print("B =", b)

print(f"\nAB = {a @ b}")

A = [1. 2. 3.]
B = [0.  5.  0.5]

AB = 11.5


In [25]:
#PRODUCTO DE MATRICES

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], float) #size 3*3
b = np.array([[1, 0, 2], [1, 1, 1], [0, 3, 0]], float) # size 3*3

print(f"A = {a}\n\n B = {b}\n")

print(f"AB = {a @ b}\n")
print(f"BA = {b @ a}")

A = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

 B = [[1. 0. 2.]
 [1. 1. 1.]
 [0. 3. 0.]]

AB = [[ 3. 11.  4.]
 [ 9. 23. 13.]
 [15. 35. 22.]]

BA = [[15. 18. 21.]
 [12. 15. 18.]
 [12. 15. 18.]]


In [46]:
# DETERMINANTE DE UNA MATRIZ
# Se usa np.linalg.det()

a = np.array([[-4, 2, 9], [5, 7, 2], [10, 14, 4]], float) # La F3 es combinacion lineal de la F2
b = np.array([[-4, 2, 9], [5, 7, 2], [3, 4, 4]], float)

print(f"Det(A) = {np.linalg.det(a)}")
print(f"Det(B) = {np.linalg.det(b)}")

Det(A) = 0.0
Det(B) = -117.00000000000003


In [49]:
#Auto-valores y Auto-vectores
# vals = valores, vecs = vectores
vals, vecs = np.linalg.eig(b)

print(f"{vals}\n\n {vecs}")

[11.43860705 -6.1120951   1.67348806]

 [[-0.41686781 -0.93169359  0.53586762]
 [-0.71974047  0.33322464 -0.68719793]
 [-0.55515304  0.14459735  0.49051493]]
