## Funciones Universales Binarias

* Operaciones elemento a elemento
* Toman dos arrays y devuelven 1 o más arrays

#### Funciones:

* add
* substract
* multiply
* divide, floor_divide (división y división truncada)
* array_equal (si arrays son iguales (boolean))
* power (array1 ^ array2)
* fmin (minimo entre cada elemento, ignora NaN (Not a Number))
* fmax (máximo entre cada elemento, ignora NaN)

In [4]:
import numpy as np

arr = np.array([5, 21, 28, 25])
arr2 = np.array([22, 8, 10, 40])

In [5]:
np.add(arr, arr2)

array([27, 29, 38, 65])

In [6]:
np.subtract(arr, arr2)

array([-17,  13,  18, -15])

In [7]:
np.multiply(arr, arr2)

array([ 110,  168,  280, 1000])

In [9]:
np.divide(arr, arr2)

array([0.22727273, 2.625     , 2.8       , 0.625     ])

In [10]:
np.array_equal(arr, arr2)

False

In [12]:
np.fmin(arr, arr2)

array([ 5,  8, 10, 25])

In [13]:
np.fmax(arr, arr2)

array([22, 21, 28, 40])