In [2]:
import numpy as np

In [3]:
#np.random.rand escoge valores aleatorios entre 0 y 1
#np.random.rand(n filas, n columnas), recibe como argumento el tamaño del array
arr_float = np.random.rand(3, 3)
arr_float2 = np.random.rand(3, 4)
print(f"arr_float = {arr_float}\n\n arr_float2 = {arr_float2}")

arr_float = [[0.17199302 0.12306425 0.57727442]
 [0.64834055 0.36340725 0.64306711]
 [0.5568646  0.90293416 0.32907223]]

 arr_float2 = [[0.36029715 0.21666817 0.1204003  0.27794998]
 [0.61483593 0.65437751 0.1689259  0.9261187 ]
 [0.15311164 0.47797569 0.50260939 0.62651381]]


In [19]:
#np.random.randint(limite, size=(m, n)), escoge numeros al azar hasta el limite
arr_integer = np.random.randint(5, size=(3, 3))
arr_integer2 = np.random.randint(50, size=(3,2))

print(f"arr_integer = \n{arr_integer}\n\n arr_integer2 = \n{arr_integer2}")

arr_integer = 
[[1 4 0]
 [4 0 0]
 [1 3 3]]

 arr_integer2 = 
[[30 32]
 [42 12]
 [14  5]]


In [22]:
#np.full(size, number), muestra matriz con solo numeros = n

arr_n = np.full((3,3), 21)
arr_n

array([[21, 21, 21],
       [21, 21, 21],
       [21, 21, 21]])

In [23]:
arr = np.arange(0, 20, 4)
arr

array([ 0,  4,  8, 12, 16])

In [25]:
#np.append, para ageregar al final del array
np.append(arr, [21, 22, 23])

array([ 0,  4,  8, 12, 16, 21, 22, 23])

In [26]:
#np.insert, para agregar en posicion especifica
np.insert(arr, 0, [21, 22, 23])

array([21, 22, 23,  0,  4,  8, 12, 16])

In [27]:
#np.delete(arr, position, axis=(0 or 1)), axis = 1 (eje horizontal(columnas)), axis = 0 (eje vertical(filas))
#axes: https://www.sharpsightlabs.com/blog/numpy-axes-explained/
np.delete(arr_integer, 1, axis=0)

array([[1, 4, 0],
       [1, 3, 3]])

In [28]:
np.delete(arr_integer, 1, axis=1)

array([[1, 0],
       [4, 0],
       [1, 3]])