In [15]:
import numpy as np

arr_int = np.random.randint(90, size=(4, 3))
arr_int

array([[63, 25, 29],
       [ 1, 11, 64],
       [16, 21, 20],
       [33, 58, 70]])

In [41]:
#Accediendo al método astype, para mostrar los números como decimales
arr_int.astype(float)

array([[54., 83., 62.],
       [71., 52.,  8.],
       [55., 52.,  2.],
       [13., 75., 67.]])

In [23]:
#Ordenando el ultimo eje del array
print(arr_int)

sortedArray = np.sort(arr_int)
print(f"\nSorted array: \n{sortedArray}") #En este caso el último eje es (axis=1) el horizontal


[[63 25 29]
 [ 1 11 64]
 [16 21 20]
 [33 58 70]]

Sorted array: 
[[25 29 63]
 [ 1 11 64]
 [16 20 21]
 [33 58 70]]


In [38]:
#Aplando un array y ordenándolo

arr_flatSorted = np.sort(arr_int, None)
print(arr_flatSorted)

[ 1 11 16 20 21 25 29 33 58 63 64 70]


In [24]:
#Ordenando el array verticalmente, axis=0
sortedArray = np.sort(arr_int, axis=0)
print(f"\nSorted array: \n{sortedArray}")


Sorted array: 
[[ 1 11 20]
 [16 21 29]
 [33 25 64]
 [63 58 70]]


In [30]:
#Modificando las dimensiones de un array, reshape
arr_int = arr_int.reshape(6, 2)
arr_int

array([[63, 25],
       [29,  1],
       [11, 64],
       [16, 21],
       [20, 33],
       [58, 70]])

In [31]:
arr_int = arr_int.reshape(2, 6)
arr_int

array([[63, 25, 29,  1, 11, 64],
       [16, 21, 20, 33, 58, 70]])

In [54]:
#Aplanando array, Flatten.  Se vuelve un array unidimensional(vector)

arr_flat = arr_int.flatten()

print(arr_flat)

[63 25 29  1 11 64 16 21 20 33 58 70]


In [39]:
#Transformando un array en lista
arr_to_list = arr_int.tolist()
arr_to_list

[63, 25, 29, 1, 11, 64, 16, 21, 20, 33, 58, 70]

In [79]:
#Separando arrays
myArray = np.array(([2, 3, 4], 
                    [5, 6, 7], 
                    [8, 9, 10]))

arrays = np.split(myArray, 3)
arrays

[array([[2, 3, 4]]), array([[5, 6, 7]]), array([[ 8,  9, 10]])]

In [66]:
#Juntando arrays
np.concatenate((arrays[2], arrays[0]), axis=1)

array([[ 8,  9, 10,  2,  3,  4]])

In [67]:
np.concatenate((arrays[0], arrays[1]), axis=0)

array([[2, 3, 4],
       [5, 6, 7]])

In [86]:
# Matriz traspuesta
T_arr = myArray.T

print(f"myArray = \n{myArray}\n")
print(f"T = \n{T_arr}")



myArray = 
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

T = 
[[ 2  5  8]
 [ 3  6  9]
 [ 4  7 10]]
