## Indexación y slicing

* El slicing(filtrado) sigue la forma ````[i:j:k]````
* **i** es el indice inicial, **j** es el indice de parada, **k** es el paso.

In [7]:
import numpy as np

M = np.arange(1, 21).reshape((5, 4))
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

* Buscando elementos: M[I, J]  I = fila, J = columna

In [10]:
M[0,0]

1

In [11]:
M[1,2]

7

* Buscando Serie de filas y su serie de elementos
* Se sigue la sintaxis = [serie de filas (con i=inicio, j=final, k=paso), serie de elementos de las filas] = [i:j:k, I:J:K]

In [27]:
M[1:,] # i = 1,  en este ejm no se especifica j y k

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [22]:
M[:3:,] # j = 3, en este ejm no se especifica i y k

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
M[0:3:,] #i = 0; j = 3, es este ejm no se especifica K

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
#Especificando i,j,k

M[0:3:2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [33]:
#Especificando el elemento de la(s) fila(s) [I:J:K]

M[0:3:2, 0] # I = 0, en este ejm no se especifica J,  K = 1

array([1, 9])

In [52]:
M[0:3:2, 0:3:] #I = 0; J = 3, K = 1

array([[ 1,  2,  3],
       [ 9, 10, 11]])

In [58]:
M[0:3:2, 1:4:2] # I = 1, J = 4, K = 2

array([[ 2,  4],
       [10, 12]])

In [40]:
M[1,0:4], M[2, 1:4], M[:,0:4], M[:,1:3]

(array([5, 6, 7, 8]),
 array([10, 11, 12]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]]))

* Especificando filas y sus respectivos elementos ([filas], [elementos])

In [44]:
M[[0 , 1],[0,3]] , M[[0 , 1, 2],[0, 1, 2]]

(array([1, 8]), array([ 1,  6, 11]))

* Especificando filas y una serie de elementos ([filas], I:J:K)

In [45]:
M[[0, 1], ::2] # K = 2

array([[1, 3],
       [5, 7]])

In [64]:
M[[0, 1], 0::] # I = 0

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
M[[0, 1], :2:] # J = 2

array([[1, 2],
       [5, 6]])

In [48]:
M[[0, 2],   0:2:] # I = 0, J = 2, K = 1

array([[ 1,  2],
       [ 9, 10]])

In [50]:
M[[1, 3],  0:3:] # I = 0, J = 3, K = 1

array([[ 5,  6,  7],
       [13, 14, 15]])

In [60]:
M[[1, 3],  0:3:2] # I = 0, J = 3, K = 2

array([[ 5,  7],
       [13, 15]])

* Especificando serie de filas y sus respectivos elementos (i:j:k, [elementos])

In [63]:
M[0:3] ,M[0:3, [0 ,2]]

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[ 1,  3],
        [ 5,  7],
        [ 9, 11]]))

### Indexación booleana

In [70]:
data = np.arange(1, 11)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
data < 6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [72]:
data >= 7

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [73]:
data[data>=7]

array([ 7,  8,  9, 10])

In [76]:
data[np.array([False, False, False, False, False, False,  True,  True,  True,
        True])]

array([ 7,  8,  9, 10])

In [79]:
#Hallando los valores de data que son mayores que 6
bigger_than_6 = data > 6
bigger_than_6, data[bigger_than_6]

(array([False, False, False, False, False, False,  True,  True,  True,
         True]),
 array([ 7,  8,  9, 10]))

In [97]:
friends = np.array(['Juan', 'Sebastián', 'Julián', 'Valeria', 'Nicolás', 'Mariana'], dtype=str).reshape((3, 2))
friends

array([['Juan', 'Sebastián'],
       ['Julián', 'Valeria'],
       ['Nicolás', 'Mariana']], dtype='<U9')

In [89]:
'Juan' in friends, 'Marcela' in friends

(True, False)

In [109]:
friends[friends != 'Juan'], friends[friends == 'Julia'], friends[friends == 'Juan']

(array(['Sebastián', 'Julián', 'Valeria', 'Nicolás', 'Mariana'],
       dtype='<U9'),
 array([], dtype='<U9'),
 array(['Juan'], dtype='<U9'))